export const ADD_INGREDIENT ="ADD_INGREDIENT"
export const REMOVE_INGREDIENT ="REMOVE_INGREDIENT"
export const SET_THE_INGREDIENTS="SET_THE_INGREDIENTS"
export const SETTING_INGREDIENTS_FAILED="SETTING_INGREDIENTS_FAILED"

export const GETTING_THE_ORDERS="GETTING_THE_ORDERS"
